site_name: gileum
site_description: Loader of configuration files written in Python.
site_url: https://jjj999.github.io/gileum/

docs_dir: docs
repo_url: https://github.com/jjj999/gileum
repo_name: jjj999/gileum
copyright: Copyright &copy; 2021 Yunhyeon Jeong

theme:
  name: material
  logo: res/icon-gileum.png
  favicon: res/icon-gileum.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - search.highlight
  language: en
  palette:
    primary: orange

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jjj999/gileum

plugins:
  - search
  - mkdocstrings:
      default_handler: python
